version: "3.7"

services:
  app: 
    image: node:12-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    working_dir:  /inventory_bkend
    depends_on: 
      - mysql
    volumes:
      - ./:/inventory_bkend
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
      JWT_SECRET: 'KNOW_GOD_AND_NO_PEACE_BECAUSE_MAN_WILL_FAIL'
      process.env.NODE_ENV: development

  mysql:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - inventory-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    container_name: database-engine

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    ports:
      - "30002:80"
    environment:
      PMA_HOST: database-engine
      PMA_PORT:  3306
    volumes:
      - /sessions

volumes:
   inventory-mysql-data:
